<?php

declare(strict_types=1);

/** @var \Magelearn\CreditMemoExport\Block\Adminhtml\Creditmemo\ExportButton $block */

$exportUrl = $block->getExportUrl();
?>
<?php if ($exportUrl) : ?>
    <form method="post" action="<?= $block->escapeUrl($exportUrl) ?>">
        <?= $block->getBlockHtml('formkey') ?>

        <button type="submit"
                class="action-default scalable"
                title="<?= $block->escapeHtmlAttr(__('Export to Service')) ?>">
            <span><?= $block->escapeHtml(__('Export to Service')) ?></span>
        </button>
    </form>
<?php endif; ?>
